[package]
name = "lastwake"
version = "0.1.0"
authors = ["Michael Rodler <contact@f0rki.at>"]
edition = "2018"

[dependencies]
systemd = "0.4"
#systemd = { git = "https://github.com/jmesmon/rust-systemd" }
chrono = "0.4"
hex = "0.4"
clap = "2.33"
